# This script does two things automatically:
# - Update the documentation using roxygen2
# - Update the version number to the latest tag name and commit index + 9000
#   (e.g. tag "v1.2.3" and commit #5 in that tag will lead to "1.2.3.9005")

# Run on any push
on:
  push:
    branches: '**'

name: Update docs and version number

jobs:
  Update-docs-and-version:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # Set up R (current stable version) and developer tools
      - uses: actions/checkout@v3
      # - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          # use RStudio Package Manager (RSPM) to quickly install packages
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2
          
      # Run the updates
      - name: Update Documentation
        run: |
          Rscript -e "roxygen2::roxygenise()"
      - name: Update Version Number
        run: |
          # get latest tags to create it
          git pull --tags
          currenttagfull=`git describe --tags | sed 's/v//'`
          if [ "$currenttag" = "" ]; then
            currenttagfull="0.0.1"
          fi
          currenttagdashes=`echo $currenttag | grep -o "[-]" | wc -l`
          echo "currenttagfull is ${currenttagfull}"
          echo "currenttagdashes is ${currenttagdashes}"
          if (( "$currenttagdashes" < 1 )); then
            # so version number is like "1.0.0", commit nr is 0
            currentcommit=0
          else
            currentcommit=`git describe --tags | sed 's/.*-\(.*\)-.*/\1/'`
          fi
          # combine tag (e.g. 1.2.3) and commit number (like 5) increased by 9000 to indicate beta version
          currentversion="$currenttag.$((currentcommit + 9000))" # results in e.g. 1.2.3.9005
          echo "currentversion=${currentversion}" >> $GITHUB_ENV
          # set version number to files DESCRIPTION and NEWS.md
          sed -i -- "s/^Version: .*/Version: ${currentversion}/" DESCRIPTION
          if [ -e "NEWS.md" ]; then
            sed -i -- "1s/.*/# v${currentversion}/" NEWS.md
          fi
          rm *-- || true
      
      # Send updates to repo using GH Actions bot
      - name: Commit to Current Branch
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -am "Update version to v${{ env.currentversion }}" --author="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
          git push origin ${GITHUB_REF##*/}
