# This workflow does two things:
# - Update the R package documentation using roxygen2
# - Provide automated semantic versioning by analysing the latest tag name and commit index + 9000
#   - tag "v1.2.3" and commit #5 in that tag will lead to "1.2.3.9005"
#   - no tag and commit #5 will lead to "0.0.1.9005"
#   - The files DESCRIPTION and NEWS.md will be updated

# Run on any push
on:
  push:
    branches: '**'

name: Update docs and version number

jobs:
  Update-docs-and-version:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # Set up R (current stable version) and developer tools
      - uses: actions/checkout@v3
      # - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          # use RStudio Package Manager (RSPM) to quickly install packages
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2
          
      # Run the updates
      - name: Update R Documentation
        run: |
          Rscript -e "roxygen2::roxygenise()"
          
      - name: Update Version Number
        run: |
          # get latest tags to create it
          git pull --tags
          currenttag=`git describe --tags | sed 's/v//'`
          if [ "$currenttag" = "" ]; then
            # there is no tag, so set tag to 0.0.1 and commit index to current count
            echo "Message: no git tags found, setting version to 0.0.1.*"
            currenttag="0.0.1"
            git shortlog
            git pull --force
            # currentcommit=`git rev-list --count ${GITHUB_REF##*/}`
            git shortlog | grep -E '^[ ]+\w+'
            currentcommit=`git shortlog | grep -E '^[ ]+\w+' | wc -l`
          else
            # there is a tag, so base version number on that
            echo "Message: tag ${currenttag} found"
            commitcount=`echo $currenttag | grep -o "[-]" | wc -l`
            if (( "$commitcount" < 1 )); then
              # tag is new, so commit index must be 0
              echo "Message: no previous commits found in tag ${currenttag}"
              currentcommit=0
            else
              # determine commit count within tag
              currentcommit=`git describe --tags | sed 's/.*-\(.*\)-.*/\1/'`
              echo "Message: ${currentcommit} previous commits found in tag ${currenttag}"
            fi
          fi
          # combine tag (e.g. 1.2.3) and commit number (like 5) increased by 9000 to indicate beta version
          currentversion="$currenttag.$((currentcommit + 9000))" # results in e.g. 1.2.3.9005
          echo "Message: current version will be v${currentversion}"
          echo "currentversion=${currentversion}" >> $GITHUB_ENV
          # set version number to files DESCRIPTION and NEWS.md
          sed -i -- "s/^Version: .*/Version: ${currentversion}/" DESCRIPTION
          if [ -e "NEWS.md" ]; then
            sed -i -- "1s/.*/# v${currentversion}/" NEWS.md
          else
            echo "Message: no NEWS.md found"
          fi
          # rm *-- || true # required for macOS
      
      # Send updates to repo using GH Actions bot
      - name: Commit to Current Branch
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -am "Auto-update versioning to v${{ env.currentversion }}" --author="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
            git push origin ${GITHUB_REF##*/}
          else 
            echo "No git changes, nothing to commit"
          fi
