# Create a website from the R documentation using pkgdown
# Git commit and push to the 'gh-pages' branch

on:
  push:
    # only on main
    branches: 'main'

name: Update website

jobs:
  update-website:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # Set up R (current stable version) and developer tools
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
            r-version: "release"
            # use RStudio Package Manager (RSPM) to quickly install packages
            use-public-rspm: true
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown

      # Send updates to repo using GH Actions bot
      - name: Create website in separate branch
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Rscript -e 'pkgdown::build_favicons()'
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, clean = TRUE, install = TRUE, branch = "gh-pages")'
